//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager memorizzata nella cache da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        ///   le ricerche di risorse eseguite con questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .BMP.GIF.JPEG.PNG.TIFF.WMF.EMF.PPTX.PPS.HTML.HTM.XHTML.XML.DOCX.RTF.ODT.SWX.WPD.ODS.SXC.ODP.SXI.ODG.SXD.XLSX.CSV.TXT.P7M.PDF.
        /// </summary>
        internal static string AllowExtension {
            get {
                return ResourceManager.GetString("AllowExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTROLLANTE.
        /// </summary>
        internal static string CONTROLLANTENA {
            get {
                return ResourceManager.GetString("CONTROLLANTENA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTROLLATA SENZA ALTRO RPD.
        /// </summary>
        internal static string CONTROLLATANO {
            get {
                return ResourceManager.GetString("CONTROLLATANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONTROLLATA CON ALTRO RPD.
        /// </summary>
        internal static string CONTROLLATASI {
            get {
                return ResourceManager.GetString("CONTROLLATASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ingresso.
        /// </summary>
        internal static string EtichettaElettronicaIngresso {
            get {
                return ResourceManager.GetString("EtichettaElettronicaIngresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Interno.
        /// </summary>
        internal static string EtichettaElettronicaInterno {
            get {
                return ResourceManager.GetString("EtichettaElettronicaInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uscita.
        /// </summary>
        internal static string EtichettaElettronicaUscita {
            get {
                return ResourceManager.GetString("EtichettaElettronicaUscita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2 - Documento con firma NON valida..
        /// </summary>
        internal static string FirmaNo {
            get {
                return ResourceManager.GetString("FirmaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3 - Documento con HASH NON conforme..
        /// </summary>
        internal static string HashNo {
            get {
                return ResourceManager.GetString("HashNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C:\\SIAV\\Images\\.
        /// </summary>
        internal static string IMAGESPATH {
            get {
                return ResourceManager.GetString("IMAGESPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INIPEC.
        /// </summary>
        internal static string INIPEC {
            get {
                return ResourceManager.GetString("INIPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 4 - Non è stata individuata la scheda indicata per questo protocollo..
        /// </summary>
        internal static string InternalAttachKo {
            get {
                return ResourceManager.GetString("InternalAttachKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Società controllata.
        /// </summary>
        internal static string InternalNoteDPO {
            get {
                return ResourceManager.GetString("InternalNoteDPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IPA.
        /// </summary>
        internal static string IPA {
            get {
                return ResourceManager.GetString("IPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3.
        /// </summary>
        internal static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 0.
        /// </summary>
        internal static string lFieldID {
            get {
                return ResourceManager.GetString("lFieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C:\\SIAV\\Corelog\\.
        /// </summary>
        internal static string LOGPATH {
            get {
                return ResourceManager.GetString("LOGPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NESSUNO.
        /// </summary>
        internal static string NESSUNO {
            get {
                return ResourceManager.GetString("NESSUNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Documento originale.
        /// </summary>
        internal static string NoteMainDocOriginale {
            get {
                return ResourceManager.GetString("NoteMainDocOriginale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Documento Stampabile.
        /// </summary>
        internal static string NoteMainDocStampabile {
            get {
                return ResourceManager.GetString("NoteMainDocStampabile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NO GRUPPO.
        /// </summary>
        internal static string NO_GRUPPONA {
            get {
                return ResourceManager.GetString("NO_GRUPPONA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DPO.
        /// </summary>
        internal static string OGGETTO_DPO {
            get {
                return ResourceManager.GetString("OGGETTO_DPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Garante.
        /// </summary>
        internal static string PasswordPfx {
            get {
                return ResourceManager.GetString("PasswordPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C:\Siav\Certificato\Garante.pfx.
        /// </summary>
        internal static string PathPfx {
            get {
                return ResourceManager.GetString("PathPfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PERSONA FISICA.
        /// </summary>
        internal static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PERSONA GIURIDICA.
        /// </summary>
        internal static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1 - Documento protocollato correttamente..
        /// </summary>
        internal static string ProtOk {
            get {
                return ResourceManager.GetString("ProtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a false.
        /// </summary>
        internal static string QUEUE_LOG_ALL {
            get {
                return ResourceManager.GetString("QUEUE_LOG_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a true.
        /// </summary>
        internal static string QUEUE_LOG_ON_ERROR {
            get {
                return ResourceManager.GetString("QUEUE_LOG_ON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 50.
        /// </summary>
        internal static string QUEUE_SIZE {
            get {
                return ResourceManager.GetString("QUEUE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string ReadFromArchiflow {
            get {
                return ResourceManager.GetString("ReadFromArchiflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 13.
        /// </summary>
        internal static string shArchive {
            get {
                return ResourceManager.GetString("shArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 28.
        /// </summary>
        internal static string shDocType {
            get {
                return ResourceManager.GetString("shDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Arial.
        /// </summary>
        internal static string SignatureFontName {
            get {
                return ResourceManager.GetString("SignatureFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 9.
        /// </summary>
        internal static string SignatureFontSize {
            get {
                return ResourceManager.GetString("SignatureFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPDP.Ufficio.PROTOCOLLO.I.{0}.{1}.
        /// </summary>
        internal static string SignatureIngresso {
            get {
                return ResourceManager.GetString("SignatureIngresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPDP.Ufficio.PROTOCOLLO.D.{0}.{1}.
        /// </summary>
        internal static string SignatureInterno {
            get {
                return ResourceManager.GetString("SignatureInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1.
        /// </summary>
        internal static string SignaturePageNum {
            get {
                return ResourceManager.GetString("SignaturePageNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPDP.Ufficio.PROTOCOLLO.U.{0}.{1}.
        /// </summary>
        internal static string SignatureUscita {
            get {
                return ResourceManager.GetString("SignatureUscita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5.
        /// </summary>
        internal static string SignatureX {
            get {
                return ResourceManager.GetString("SignatureX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5.
        /// </summary>
        internal static string SignatureY {
            get {
                return ResourceManager.GetString("SignatureY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATTIVA.
        /// </summary>
        internal static string StateActive {
            get {
                return ResourceManager.GetString("StateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INVALIDA.
        /// </summary>
        internal static string StateBad {
            get {
                return ResourceManager.GetString("StateBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MODIFICATA.
        /// </summary>
        internal static string StateOld {
            get {
                return ResourceManager.GetString("StateOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C:\\SIAV\\Template\\.
        /// </summary>
        internal static string TEMPLATEPATH {
            get {
                return ResourceManager.GetString("TEMPLATEPATH", resourceCulture);
            }
        }
    }
}
