//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCF_Ws.WsClassifica {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseSearcher", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.ValueObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificazioneBaseSearcher))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificaDocumentoSearcher))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloDocumentoSearcher))]
    public partial class BaseSearcher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotPageItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotPageItems {
            get {
                return this.TotPageItemsField;
            }
            set {
                if ((this.TotPageItemsField.Equals(value) != true)) {
                    this.TotPageItemsField = value;
                    this.RaisePropertyChanged("TotPageItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificazioneBaseSearcher", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.BaseC" +
        "lass")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificaDocumentoSearcher))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloDocumentoSearcher))]
    public partial class ClassificazioneBaseSearcher : OCF_Ws.WsClassifica.BaseSearcher {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.CoupleIdentifier AOOKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.StatusType StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.CoupleIdentifier UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.CoupleIdentifier AOOKey {
            get {
                return this.AOOKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AOOKeyField, value) != true)) {
                    this.AOOKeyField = value;
                    this.RaisePropertyChanged("AOOKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.StatusType Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.CoupleIdentifier UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificaDocumentoSearcher", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Titolario.Se" +
        "archer")]
    [System.SerializableAttribute()]
    public partial class ClassificaDocumentoSearcher : OCF_Ws.WsClassifica.ClassificazioneBaseSearcher {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.DocumentIdentifier DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.ClassificaDocIdentifier IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.TitolarioItemIdentifier TitolarioItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.DocumentIdentifier DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.ClassificaDocIdentifier Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.TitolarioItemIdentifier TitolarioItemId {
            get {
                return this.TitolarioItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TitolarioItemIdField, value) != true)) {
                    this.TitolarioItemIdField = value;
                    this.RaisePropertyChanged("TitolarioItemId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FascicoloDocumentoSearcher", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Fascicoli.Se" +
        "archer")]
    [System.SerializableAttribute()]
    public partial class FascicoloDocumentoSearcher : OCF_Ws.WsClassifica.ClassificazioneBaseSearcher {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDoc_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.DocumentIdentifier DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.FascicoloIdentifier Fascicolo_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.FascicoloDocIdentifier IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.BaseIdentifier UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDoc_Id {
            get {
                return this.ClassDoc_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassDoc_IdField, value) != true)) {
                    this.ClassDoc_IdField = value;
                    this.RaisePropertyChanged("ClassDoc_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.DocumentIdentifier DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.FascicoloIdentifier Fascicolo_Id {
            get {
                return this.Fascicolo_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Fascicolo_IdField, value) != true)) {
                    this.Fascicolo_IdField = value;
                    this.RaisePropertyChanged("Fascicolo_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.FascicoloDocIdentifier Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.BaseIdentifier UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoupleIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.ValueObject")]
    [System.SerializableAttribute()]
    public partial class CoupleIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusType", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Types")]
    public enum StatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Draft = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Obsolete = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificaDocIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Titolario.Id" +
        "entifier")]
    [System.SerializableAttribute()]
    public partial class ClassificaDocIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Ident" +
        "ifier")]
    [System.SerializableAttribute()]
    public partial class DocumentIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FascicoloIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Fascicoli.Id" +
        "entifier")]
    [System.SerializableAttribute()]
    public partial class FascicoloIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FascicoloDocIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Fascicolo.Id" +
        "entifier")]
    [System.SerializableAttribute()]
    public partial class FascicoloDocIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.ValueObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificaDocIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.DocumentIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloDocIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.TitolarioItemIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.CoupleIdentifier))]
    public partial class BaseIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TitolarioItemIdentifier", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.TitolarioIte" +
        "m.Identifier")]
    [System.SerializableAttribute()]
    public partial class TitolarioItemIdentifier : OCF_Ws.WsClassifica.BaseIdentifier {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.Types")]
    public enum ResultInfo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FascicoloDocumentoEntity", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Fascicoli.Va" +
        "lueObject")]
    [System.SerializableAttribute()]
    public partial class FascicoloDocumentoEntity : OCF_Ws.WsClassifica.BaseFascicoloDocumento {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDoc_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataClassificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.DocumentIdentifier DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDoc_Id {
            get {
                return this.ClassDoc_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassDoc_IdField, value) != true)) {
                    this.ClassDoc_IdField = value;
                    this.RaisePropertyChanged("ClassDoc_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataClassifica {
            get {
                return this.DataClassificaField;
            }
            set {
                if ((this.DataClassificaField.Equals(value) != true)) {
                    this.DataClassificaField = value;
                    this.RaisePropertyChanged("DataClassifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.DocumentIdentifier DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sorting {
            get {
                return this.SortingField;
            }
            set {
                if ((this.SortingField.Equals(value) != true)) {
                    this.SortingField = value;
                    this.RaisePropertyChanged("Sorting");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseValueObject", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.ValueObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.BaseClassificaDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificaDocumentoEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.BaseFascicoloDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloDocumentoEntity))]
    public partial class BaseValueObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCheckedOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCheckedOut {
            get {
                return this.IsCheckedOutField;
            }
            set {
                if ((this.IsCheckedOutField.Equals(value) != true)) {
                    this.IsCheckedOutField = value;
                    this.RaisePropertyChanged("IsCheckedOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseClassificaDocumento", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Titolario.Va" +
        "lueObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.ClassificaDocumentoEntity))]
    public partial class BaseClassificaDocumento : OCF_Ws.WsClassifica.BaseValueObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseFascicoloDocumento> FascDocCollField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.ClassificaDocIdentifier IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.TitolarioItemIdentifier TitolarioItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseFascicoloDocumento> FascDocColl {
            get {
                return this.FascDocCollField;
            }
            set {
                if ((object.ReferenceEquals(this.FascDocCollField, value) != true)) {
                    this.FascDocCollField = value;
                    this.RaisePropertyChanged("FascDocColl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.ClassificaDocIdentifier Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Primary {
            get {
                return this.PrimaryField;
            }
            set {
                if ((this.PrimaryField.Equals(value) != true)) {
                    this.PrimaryField = value;
                    this.RaisePropertyChanged("Primary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.TitolarioItemIdentifier TitolarioItemId {
            get {
                return this.TitolarioItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TitolarioItemIdField, value) != true)) {
                    this.TitolarioItemIdField = value;
                    this.RaisePropertyChanged("TitolarioItemId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificaDocumentoEntity", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Titolario.Va" +
        "lueObject")]
    [System.SerializableAttribute()]
    public partial class ClassificaDocumentoEntity : OCF_Ws.WsClassifica.BaseClassificaDocumento {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataClassificaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.DocumentIdentifier DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataClassifica {
            get {
                return this.DataClassificaField;
            }
            set {
                if ((this.DataClassificaField.Equals(value) != true)) {
                    this.DataClassificaField = value;
                    this.RaisePropertyChanged("DataClassifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.DocumentIdentifier DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdField, value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sorting {
            get {
                return this.SortingField;
            }
            set {
                if ((this.SortingField.Equals(value) != true)) {
                    this.SortingField = value;
                    this.RaisePropertyChanged("Sorting");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFascicoloDocumento", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Fascicoli.Va" +
        "lueObject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsClassifica.FascicoloDocumentoEntity))]
    public partial class BaseFascicoloDocumento : OCF_Ws.WsClassifica.BaseValueObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.FascicoloIdentifier Fascicolo_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.FascicoloDocIdentifier IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VisibilityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.FascicoloIdentifier Fascicolo_Id {
            get {
                return this.Fascicolo_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Fascicolo_IdField, value) != true)) {
                    this.Fascicolo_IdField = value;
                    this.RaisePropertyChanged("Fascicolo_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.FascicoloDocIdentifier Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Primary {
            get {
                return this.PrimaryField;
            }
            set {
                if ((this.PrimaryField.Equals(value) != true)) {
                    this.PrimaryField = value;
                    this.RaisePropertyChanged("Primary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Visibility {
            get {
                return this.VisibilityField;
            }
            set {
                if ((this.VisibilityField.Equals(value) != true)) {
                    this.VisibilityField = value;
                    this.RaisePropertyChanged("Visibility");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
        "Object")]
    [System.SerializableAttribute()]
    public partial class ClassificationExceptionDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsClassifica.ClassificationExceptionSeverity SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HResultCode {
            get {
                return this.HResultCodeField;
            }
            set {
                if ((this.HResultCodeField.Equals(value) != true)) {
                    this.HResultCodeField = value;
                    this.RaisePropertyChanged("HResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsClassifica.ClassificationExceptionSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificationExceptionSeverity", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
        "Object")]
    public enum ClassificationExceptionSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cesSuccessInfo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cesApplicationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cesDbError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cesError = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsClassifica.iClassificaServiceContract")]
    public interface iClassificaServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/ReadFascicoloDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/ReadFascicoloDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/ReadFascicoloDocumentoClassificatio" +
            "nExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo ReadFascicoloDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.FascicoloDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.FascicoloDocumentoSearcher Searcher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/ReadClassificaDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/ReadClassificaDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/ReadClassificaDocumentoClassificati" +
            "onExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo ReadClassificaDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.ClassificaDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.ClassificaDocumentoSearcher Searcher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/ReadClassFascDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/ReadClassFascDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/ReadClassFascDocumentoClassificatio" +
            "nExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo ReadClassFascDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.ClassificaDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocumentoSearcher SearcherDoc, OCF_Ws.WsClassifica.FascicoloDocumentoSearcher SearcherFasc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/ReadClassificaCodeColl", ReplyAction="http://tempuri.org/iClassificaServiceContract/ReadClassificaCodeCollResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/ReadClassificaCodeCollClassificatio" +
            "nExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo ReadClassificaCodeColl(out System.Collections.Generic.List<string> ListClassCode, out System.Collections.Generic.List<string> ListFascCode, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicolo", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicoloResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicoloClassifica" +
            "tionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaFascicolo(out OCF_Ws.WsClassifica.FascicoloDocIdentifier outPk, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.FascicoloDocumentoEntity value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicolo2", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicolo2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaFascicolo2Classific" +
            "ationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaFascicolo2(out OCF_Ws.WsClassifica.FascicoloDocIdentifier outPk, string strSessionId, OCF_Ws.WsClassifica.FascicoloDocumentoEntity value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumentoClassifica" +
            "tionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento1", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento1Classific" +
            "ationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento1(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento2", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocumento2Classific" +
            "ationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento2(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, string strSessionId, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocColl", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocCollResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocCollClassificati" +
            "onExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocColl(OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.DocumentIdentifier DocumentId, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocColl2", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocColl2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertClassificaDocColl2Classificat" +
            "ionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocColl2(string strSessionId, OCF_Ws.WsClassifica.DocumentIdentifier DocumentId, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocColl", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocCollRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocCollClassif" +
            "icationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertMultiClassificaDocColl(OCF_Ws.WsClassifica.BaseIdentifier UtenteId, bool DelExisting, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocColl2", ReplyAction="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocColl2Respon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/InsertMultiClassificaDocColl2Classi" +
            "ficationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo InsertMultiClassificaDocColl2(string strSessionId, bool DelExisting, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumentoClassificat" +
            "ionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo DeleteFascicoloDocumento(out bool ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumento2", ReplyAction="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumento2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/DeleteFascicoloDocumento2Classifica" +
            "tionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo DeleteFascicoloDocumento2(out bool ReturnValue, string strSessionId, OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumentoClassifica" +
            "tionExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo DeleteClassificaDocumento(out bool ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumento2", ReplyAction="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumento2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/DeleteClassificaDocumento2Classific" +
            "ationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo DeleteClassificaDocumento2(out bool ReturnValue, string strSessionId, OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/SetPrimaryFascicoloDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/SetPrimaryFascicoloDocumentoRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/SetPrimaryFascicoloDocumentoClassif" +
            "icationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo SetPrimaryFascicoloDocumento(OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId, bool bPrimary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iClassificaServiceContract/SetPrimaryClassificaDocumento", ReplyAction="http://tempuri.org/iClassificaServiceContract/SetPrimaryClassificaDocumentoRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsClassifica.ClassificationExceptionDetail), Action="http://tempuri.org/iClassificaServiceContract/SetPrimaryClassificaDocumentoClassi" +
            "ficationExceptionDetailFault", Name="ClassificationExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Classification.Entities.Common.Value" +
            "Object")]
        OCF_Ws.WsClassifica.ResultInfo SetPrimaryClassificaDocumento(OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId, bool bPrimary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iClassificaServiceContractChannel : OCF_Ws.WsClassifica.iClassificaServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iClassificaServiceContractClient : System.ServiceModel.ClientBase<OCF_Ws.WsClassifica.iClassificaServiceContract>, OCF_Ws.WsClassifica.iClassificaServiceContract {
        
        public iClassificaServiceContractClient() {
        }
        
        public iClassificaServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iClassificaServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iClassificaServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iClassificaServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OCF_Ws.WsClassifica.ResultInfo ReadFascicoloDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.FascicoloDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.FascicoloDocumentoSearcher Searcher) {
            return base.Channel.ReadFascicoloDocumento(out ReturnValue, Searcher);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo ReadClassificaDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.ClassificaDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.ClassificaDocumentoSearcher Searcher) {
            return base.Channel.ReadClassificaDocumento(out ReturnValue, Searcher);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo ReadClassFascDocumento(out System.Collections.Generic.List<OCF_Ws.WsClassifica.ClassificaDocumentoEntity> ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocumentoSearcher SearcherDoc, OCF_Ws.WsClassifica.FascicoloDocumentoSearcher SearcherFasc) {
            return base.Channel.ReadClassFascDocumento(out ReturnValue, UtenteId, SearcherDoc, SearcherFasc);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo ReadClassificaCodeColl(out System.Collections.Generic.List<string> ListClassCode, out System.Collections.Generic.List<string> ListFascCode, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl) {
            return base.Channel.ReadClassificaCodeColl(out ListClassCode, out ListFascCode, DocIdColl);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaFascicolo(out OCF_Ws.WsClassifica.FascicoloDocIdentifier outPk, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.FascicoloDocumentoEntity value) {
            return base.Channel.InsertClassificaFascicolo(out outPk, UtenteId, value);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaFascicolo2(out OCF_Ws.WsClassifica.FascicoloDocIdentifier outPk, string strSessionId, OCF_Ws.WsClassifica.FascicoloDocumentoEntity value) {
            return base.Channel.InsertClassificaFascicolo2(out outPk, strSessionId, value);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value) {
            return base.Channel.InsertClassificaDocumento(out outPk, value);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento1(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value) {
            return base.Channel.InsertClassificaDocumento1(out outPk, UtenteId, value);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocumento2(out OCF_Ws.WsClassifica.ClassificaDocIdentifier outPk, string strSessionId, OCF_Ws.WsClassifica.ClassificaDocumentoEntity value) {
            return base.Channel.InsertClassificaDocumento2(out outPk, strSessionId, value);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocColl(OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.DocumentIdentifier DocumentId, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl) {
            return base.Channel.InsertClassificaDocColl(UtenteId, DocumentId, ref ClassDocColl);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertClassificaDocColl2(string strSessionId, OCF_Ws.WsClassifica.DocumentIdentifier DocumentId, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl) {
            return base.Channel.InsertClassificaDocColl2(strSessionId, DocumentId, ref ClassDocColl);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertMultiClassificaDocColl(OCF_Ws.WsClassifica.BaseIdentifier UtenteId, bool DelExisting, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl) {
            return base.Channel.InsertMultiClassificaDocColl(UtenteId, DelExisting, DocIdColl, ref ClassDocColl);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo InsertMultiClassificaDocColl2(string strSessionId, bool DelExisting, System.Collections.Generic.List<OCF_Ws.WsClassifica.DocumentIdentifier> DocIdColl, ref System.Collections.Generic.List<OCF_Ws.WsClassifica.BaseClassificaDocumento> ClassDocColl) {
            return base.Channel.InsertMultiClassificaDocColl2(strSessionId, DelExisting, DocIdColl, ref ClassDocColl);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo DeleteFascicoloDocumento(out bool ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId) {
            return base.Channel.DeleteFascicoloDocumento(out ReturnValue, UtenteId, FascDocId);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo DeleteFascicoloDocumento2(out bool ReturnValue, string strSessionId, OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId) {
            return base.Channel.DeleteFascicoloDocumento2(out ReturnValue, strSessionId, FascDocId);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo DeleteClassificaDocumento(out bool ReturnValue, OCF_Ws.WsClassifica.BaseIdentifier UtenteId, OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId) {
            return base.Channel.DeleteClassificaDocumento(out ReturnValue, UtenteId, ClassDocId);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo DeleteClassificaDocumento2(out bool ReturnValue, string strSessionId, OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId) {
            return base.Channel.DeleteClassificaDocumento2(out ReturnValue, strSessionId, ClassDocId);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo SetPrimaryFascicoloDocumento(OCF_Ws.WsClassifica.FascicoloDocIdentifier FascDocId, bool bPrimary) {
            return base.Channel.SetPrimaryFascicoloDocumento(FascDocId, bPrimary);
        }
        
        public OCF_Ws.WsClassifica.ResultInfo SetPrimaryClassificaDocumento(OCF_Ws.WsClassifica.ClassificaDocIdentifier ClassDocId, bool bPrimary) {
            return base.Channel.SetPrimaryClassificaDocumento(ClassDocId, bPrimary);
        }
    }
}
