using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Siav.APFlibrary.Model
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Il codice è stato generato da uno strumento.
    //     Versione runtime:4.0.30319.42000
    //
    //     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
    //     il codice viene rigenerato.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/xhtml")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.w3.org/1999/xhtml", IsNullable = false)]
    public partial class SENDOBJECT
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SENDENTITIES", typeof(SENDOBJECTSENDENTITIES))]
        [System.Xml.Serialization.XmlElementAttribute("SENDOPTION", typeof(SENDOBJECTSENDOPTION))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/xhtml")]
    public partial class SENDOBJECTSENDENTITIES
    {

        private SENDOBJECTSENDENTITIESSENDENTITY[] sENDENTITYField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SENDENTITY")]
        public SENDOBJECTSENDENTITIESSENDENTITY[] SENDENTITY
        {
            get
            {
                return this.sENDENTITYField;
            }
            set
            {
                this.sENDENTITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/xhtml")]
    public partial class SENDOBJECTSENDENTITIESSENDENTITY
    {

        private string dESCRIPTIONField;

        private string sTATUSField;

        private string idField;

        private string lEVELField;

        private string tYPEField;

        private string oPERATIONALField;

        private string sENDINGTYPEField;

        private string ccField;

        /// <remarks/>
        public string DESCRIPTION
        {
            get
            {
                return this.dESCRIPTIONField;
            }
            set
            {
                this.dESCRIPTIONField = value;
            }
        }

        /// <remarks/>
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string LEVEL
        {
            get
            {
                return this.lEVELField;
            }
            set
            {
                this.lEVELField = value;
            }
        }

        /// <remarks/>
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }

        /// <remarks/>
        public string OPERATIONAL
        {
            get
            {
                return this.oPERATIONALField;
            }
            set
            {
                this.oPERATIONALField = value;
            }
        }

        /// <remarks/>
        public string SENDINGTYPE
        {
            get
            {
                return this.sENDINGTYPEField;
            }
            set
            {
                this.sENDINGTYPEField = value;
            }
        }

        /// <remarks/>
        public string CC
        {
            get
            {
                return this.ccField;
            }
            set
            {
                this.ccField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/1999/xhtml")]
    public partial class SENDOBJECTSENDOPTION
    {

        private string iSDISABLEDRECEIVERSField;

        private string iSAUTOMATICSENDINGField;

        private string iSVISIBLEONLYDOCField;

        /// <remarks/>
        public string ISDISABLEDRECEIVERS
        {
            get
            {
                return this.iSDISABLEDRECEIVERSField;
            }
            set
            {
                this.iSDISABLEDRECEIVERSField = value;
            }
        }

        /// <remarks/>
        public string ISAUTOMATICSENDING
        {
            get
            {
                return this.iSAUTOMATICSENDINGField;
            }
            set
            {
                this.iSAUTOMATICSENDINGField = value;
            }
        }

        /// <remarks/>
        public string ISVISIBLEONLYDOC
        {
            get
            {
                return this.iSVISIBLEONLYDOCField;
            }
            set
            {
                this.iSVISIBLEONLYDOCField = value;
            }
        }
    }

}