//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCF_Ws.WsSign {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignRequest", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class RemoteSignRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.RemoteService ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.RemoteSignInfo SignInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.RemoteService Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.RemoteSignInfo SignInfo {
            get {
                return this.SignInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SignInfoField, value) != true)) {
                    this.SignInfoField = value;
                    this.RaisePropertyChanged("SignInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteService", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class RemoteService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceURL {
            get {
                return this.ServiceURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceURLField, value) != true)) {
                    this.ServiceURLField = value;
                    this.RaisePropertyChanged("ServiceURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timeout {
            get {
                return this.TimeoutField;
            }
            set {
                if ((this.TimeoutField.Equals(value) != true)) {
                    this.TimeoutField = value;
                    this.RaisePropertyChanged("Timeout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class RemoteSignInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ApplyTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CardsToSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FiscalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PdfNativeSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApplyTimestamp {
            get {
                return this.ApplyTimestampField;
            }
            set {
                if ((this.ApplyTimestampField.Equals(value) != true)) {
                    this.ApplyTimestampField = value;
                    this.RaisePropertyChanged("ApplyTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> CardsToSign {
            get {
                return this.CardsToSignField;
            }
            set {
                if ((object.ReferenceEquals(this.CardsToSignField, value) != true)) {
                    this.CardsToSignField = value;
                    this.RaisePropertyChanged("CardsToSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FiscalCode {
            get {
                return this.FiscalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FiscalCodeField, value) != true)) {
                    this.FiscalCodeField = value;
                    this.RaisePropertyChanged("FiscalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PdfNativeSignature {
            get {
                return this.PdfNativeSignatureField;
            }
            set {
                if ((this.PdfNativeSignatureField.Equals(value) != true)) {
                    this.PdfNativeSignatureField = value;
                    this.RaisePropertyChanged("PdfNativeSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.Types")]
    public enum ResultInfo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignResponse", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class RemoteSignResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.SignTaskStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnsignedHashesXmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinNumber {
            get {
                return this.PinNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PinNumberField, value) != true)) {
                    this.PinNumberField = value;
                    this.RaisePropertyChanged("PinNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.SignTaskStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusString {
            get {
                return this.StatusStringField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusStringField, value) != true)) {
                    this.StatusStringField = value;
                    this.RaisePropertyChanged("StatusString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TaskId {
            get {
                return this.TaskIdField;
            }
            set {
                if ((this.TaskIdField.Equals(value) != true)) {
                    this.TaskIdField = value;
                    this.RaisePropertyChanged("TaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnsignedHashesXml {
            get {
                return this.UnsignedHashesXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.UnsignedHashesXmlField, value) != true)) {
                    this.UnsignedHashesXmlField = value;
                    this.RaisePropertyChanged("UnsignedHashesXml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignTaskStatus", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum SignTaskStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationCompletedSuccessfully = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingPIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedSuccessfully = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceivedPIN = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HiddenPhoneNumber = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Extended = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneCallTimeout = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PinWrong = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsSign.SignFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault))]
    public partial class BaseFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsComErrorInternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalCode {
            get {
                return this.InternalCodeField;
            }
            set {
                if ((this.InternalCodeField.Equals(value) != true)) {
                    this.InternalCodeField = value;
                    this.RaisePropertyChanged("InternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComErrorInternalCode {
            get {
                return this.IsComErrorInternalCodeField;
            }
            set {
                if ((this.IsComErrorInternalCodeField.Equals(value) != true)) {
                    this.IsComErrorInternalCodeField = value;
                    this.RaisePropertyChanged("IsComErrorInternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class SignFault : OCF_Ws.WsSign.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidSessionFault : OCF_Ws.WsSign.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ArchiflowServiceExceptionDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.ArchiflowExceptionSeverity SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HResultCode {
            get {
                return this.HResultCodeField;
            }
            set {
                if ((this.HResultCodeField.Equals(value) != true)) {
                    this.HResultCodeField = value;
                    this.RaisePropertyChanged("HResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.ArchiflowExceptionSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiflowExceptionSeverity", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
    public enum ArchiflowExceptionSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessInfo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteSignTask", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class RemoteSignTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorsNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> SignedHashesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.SignTaskStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorsNumber {
            get {
                return this.ErrorsNumberField;
            }
            set {
                if ((this.ErrorsNumberField.Equals(value) != true)) {
                    this.ErrorsNumberField = value;
                    this.RaisePropertyChanged("ErrorsNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> SignedHashes {
            get {
                return this.SignedHashesField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedHashesField, value) != true)) {
                    this.SignedHashesField = value;
                    this.RaisePropertyChanged("SignedHashes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.SignTaskStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoggableBase", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.Tools.Log")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsSign.SessionInfo))]
    public partial class LoggableBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class SessionInfo : OCF_Ws.WsSign.LoggableBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CharacterSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExecutiveOfficeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OCF_Ws.WsSign.OfficeChart> ExecutiveOfficesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.Language LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginTicketUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsSign.UserLoginType LoginTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenSessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VelocisDatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VelocisServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CharacterSet {
            get {
                return this.CharacterSetField;
            }
            set {
                if ((this.CharacterSetField.Equals(value) != true)) {
                    this.CharacterSetField = value;
                    this.RaisePropertyChanged("CharacterSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFormatField, value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExecutiveOfficeCode {
            get {
                return this.ExecutiveOfficeCodeField;
            }
            set {
                if ((this.ExecutiveOfficeCodeField.Equals(value) != true)) {
                    this.ExecutiveOfficeCodeField = value;
                    this.RaisePropertyChanged("ExecutiveOfficeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OCF_Ws.WsSign.OfficeChart> ExecutiveOffices {
            get {
                return this.ExecutiveOfficesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutiveOfficesField, value) != true)) {
                    this.ExecutiveOfficesField = value;
                    this.RaisePropertyChanged("ExecutiveOffices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.Language Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginTicketUserId {
            get {
                return this.LoginTicketUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginTicketUserIdField, value) != true)) {
                    this.LoginTicketUserIdField = value;
                    this.RaisePropertyChanged("LoginTicketUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsSign.UserLoginType LoginType {
            get {
                return this.LoginTypeField;
            }
            set {
                if ((this.LoginTypeField.Equals(value) != true)) {
                    this.LoginTypeField = value;
                    this.RaisePropertyChanged("LoginType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSess {
            get {
                return this.TokenSessField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessField, value) != true)) {
                    this.TokenSessField = value;
                    this.RaisePropertyChanged("TokenSess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VelocisDatabase {
            get {
                return this.VelocisDatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.VelocisDatabaseField, value) != true)) {
                    this.VelocisDatabaseField = value;
                    this.RaisePropertyChanged("VelocisDatabase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VelocisServer {
            get {
                return this.VelocisServerField;
            }
            set {
                if ((object.ReferenceEquals(this.VelocisServerField, value) != true)) {
                    this.VelocisServerField = value;
                    this.RaisePropertyChanged("VelocisServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowId {
            get {
                return this.WorkflowIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowIdField, value) != true)) {
                    this.WorkflowIdField = value;
                    this.RaisePropertyChanged("WorkflowId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeChart", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Chart.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class OfficeChart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> ChildrenOfficesIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExecutiveOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> ChildrenOfficesIds {
            get {
                return this.ChildrenOfficesIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenOfficesIdsField, value) != true)) {
                    this.ChildrenOfficesIdsField = value;
                    this.RaisePropertyChanged("ChildrenOfficesIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExecutiveOffice {
            get {
                return this.IsExecutiveOfficeField;
            }
            set {
                if ((this.IsExecutiveOfficeField.Equals(value) != true)) {
                    this.IsExecutiveOfficeField = value;
                    this.RaisePropertyChanged("IsExecutiveOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum Language : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Italian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        German = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        French = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portuguese = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brasilian = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Romanian = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginType", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum UserLoginType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlWorkflow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlGed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlForcedGed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignTimeStampFileInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Sign.ValueObject")]
    [System.SerializableAttribute()]
    public partial class SignTimeStampFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DecryptedFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedP7MField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedP7MValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedPdfValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSignedXmlValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTimeStampValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsXmlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DecryptedFile {
            get {
                return this.DecryptedFileField;
            }
            set {
                if ((object.ReferenceEquals(this.DecryptedFileField, value) != true)) {
                    this.DecryptedFileField = value;
                    this.RaisePropertyChanged("DecryptedFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath {
            get {
                return this.FilePathField;
            }
            set {
                if ((object.ReferenceEquals(this.FilePathField, value) != true)) {
                    this.FilePathField = value;
                    this.RaisePropertyChanged("FilePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPdf {
            get {
                return this.IsPdfField;
            }
            set {
                if ((this.IsPdfField.Equals(value) != true)) {
                    this.IsPdfField = value;
                    this.RaisePropertyChanged("IsPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedP7M {
            get {
                return this.IsSignedP7MField;
            }
            set {
                if ((this.IsSignedP7MField.Equals(value) != true)) {
                    this.IsSignedP7MField = value;
                    this.RaisePropertyChanged("IsSignedP7M");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedP7MValid {
            get {
                return this.IsSignedP7MValidField;
            }
            set {
                if ((this.IsSignedP7MValidField.Equals(value) != true)) {
                    this.IsSignedP7MValidField = value;
                    this.RaisePropertyChanged("IsSignedP7MValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedPdf {
            get {
                return this.IsSignedPdfField;
            }
            set {
                if ((this.IsSignedPdfField.Equals(value) != true)) {
                    this.IsSignedPdfField = value;
                    this.RaisePropertyChanged("IsSignedPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedPdfValid {
            get {
                return this.IsSignedPdfValidField;
            }
            set {
                if ((this.IsSignedPdfValidField.Equals(value) != true)) {
                    this.IsSignedPdfValidField = value;
                    this.RaisePropertyChanged("IsSignedPdfValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedXml {
            get {
                return this.IsSignedXmlField;
            }
            set {
                if ((this.IsSignedXmlField.Equals(value) != true)) {
                    this.IsSignedXmlField = value;
                    this.RaisePropertyChanged("IsSignedXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSignedXmlValid {
            get {
                return this.IsSignedXmlValidField;
            }
            set {
                if ((this.IsSignedXmlValidField.Equals(value) != true)) {
                    this.IsSignedXmlValidField = value;
                    this.RaisePropertyChanged("IsSignedXmlValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTimeStamp {
            get {
                return this.IsTimeStampField;
            }
            set {
                if ((this.IsTimeStampField.Equals(value) != true)) {
                    this.IsTimeStampField = value;
                    this.RaisePropertyChanged("IsTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTimeStampValid {
            get {
                return this.IsTimeStampValidField;
            }
            set {
                if ((this.IsTimeStampValidField.Equals(value) != true)) {
                    this.IsTimeStampValidField = value;
                    this.RaisePropertyChanged("IsTimeStampValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsXml {
            get {
                return this.IsXmlField;
            }
            set {
                if ((this.IsXmlField.Equals(value) != true)) {
                    this.IsXmlField = value;
                    this.RaisePropertyChanged("IsXml");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigestTarget", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum DigestTarget : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P7m = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tsd = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignServiceType", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum SignServiceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArubaHSM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Telecom = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Infocert = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ItAgileCoSign = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfocertLcare = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsSign.ISignServiceContract")]
    public interface ISignServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/InitializeSignRequest", ReplyAction="http://tempuri.org/ISignServiceContract/InitializeSignRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/InitializeSignRequestInvalidSessionFaultF" +
            "ault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.SignFault), Action="http://tempuri.org/ISignServiceContract/InitializeSignRequestSignFaultFault", Name="SignFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/InitializeSignRequestArchiflowServiceExce" +
            "ptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo InitializeSignRequest(out OCF_Ws.WsSign.RemoteSignResponse oRemoteSignResponse, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/ConfirmSignRequest", ReplyAction="http://tempuri.org/ISignServiceContract/ConfirmSignRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/ConfirmSignRequestInvalidSessionFaultFaul" +
            "t", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/ConfirmSignRequestArchiflowServiceExcepti" +
            "onDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo ConfirmSignRequest(out OCF_Ws.WsSign.RemoteSignTask oRemoteSignTask, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest, string strXmlUnsignedHashes, long nTaskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/AbortSignRequest", ReplyAction="http://tempuri.org/ISignServiceContract/AbortSignRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/AbortSignRequestInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/AbortSignRequestArchiflowServiceException" +
            "DetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo AbortSignRequest(string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest, long nTaskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetUserCertificate", ReplyAction="http://tempuri.org/ISignServiceContract/GetUserCertificateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetUserCertificateInvalidSessionFaultFaul" +
            "t", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetUserCertificateArchiflowServiceExcepti" +
            "onDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetUserCertificate(out string strCertificate, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetSignTimeStampFileInfo", ReplyAction="http://tempuri.org/ISignServiceContract/GetSignTimeStampFileInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetSignTimeStampFileInfoInvalidSessionFau" +
            "ltFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetSignTimeStampFileInfoArchiflowServiceE" +
            "xceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetSignTimeStampFileInfo(out OCF_Ws.WsSign.SignTimeStampFileInfo oSignTimeStampFileInfo, OCF_Ws.WsSign.SessionInfo oSessionInfo, string FileName, byte[] FileContent, bool bDecryptFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetDigestForMassiveSign", ReplyAction="http://tempuri.org/ISignServiceContract/GetDigestForMassiveSignResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetDigestForMassiveSignInvalidSessionFaul" +
            "tFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetDigestForMassiveSignArchiflowServiceEx" +
            "ceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetDigestForMassiveSign(out string strXMLOut, string strGuidConnect, System.Collections.Generic.List<System.Guid> oCardIds, byte[] Certificate, OCF_Ws.WsSign.DigestTarget Target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetAttachmentsDigestForMassiveSign", ReplyAction="http://tempuri.org/ISignServiceContract/GetAttachmentsDigestForMassiveSignRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetAttachmentsDigestForMassiveSignInvalid" +
            "SessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetAttachmentsDigestForMassiveSignArchifl" +
            "owServiceExceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetAttachmentsDigestForMassiveSign(out string strXMLOut, string strGuidConnect, System.Guid oCardId, System.Collections.Generic.List<int> oAttNames, byte[] Certificate, OCF_Ws.WsSign.DigestTarget Target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/UploadCardsSigned", ReplyAction="http://tempuri.org/ISignServiceContract/UploadCardsSignedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/UploadCardsSignedInvalidSessionFaultFault" +
            "", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/UploadCardsSignedArchiflowServiceExceptio" +
            "nDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo UploadCardsSigned(out string strXMLOut, string strGuidConnect, string strXmlSignedHashes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/UploadAttachmentsSigned", ReplyAction="http://tempuri.org/ISignServiceContract/UploadAttachmentsSignedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/UploadAttachmentsSignedInvalidSessionFaul" +
            "tFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/UploadAttachmentsSignedArchiflowServiceEx" +
            "ceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo UploadAttachmentsSigned(out string strXMLOut, string strGuidConnect, string strXmlSignedHashes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/IsX509Certificate2Valid", ReplyAction="http://tempuri.org/ISignServiceContract/IsX509Certificate2ValidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/IsX509Certificate2ValidInvalidSessionFaul" +
            "tFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/IsX509Certificate2ValidArchiflowServiceEx" +
            "ceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo IsX509Certificate2Valid(out System.Collections.Generic.List<string> logList, string strGuidConnect, System.Security.Cryptography.X509Certificates.X509Certificate2 oX509Certificate, System.Nullable<System.DateTime> oCheckDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetRemoteSignType", ReplyAction="http://tempuri.org/ISignServiceContract/GetRemoteSignTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetRemoteSignTypeInvalidSessionFaultFault" +
            "", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetRemoteSignTypeArchiflowServiceExceptio" +
            "nDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetRemoteSignType(out OCF_Ws.WsSign.SignServiceType SignType, string strGuidConnect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignServiceContract/GetBulkSignSettings", ReplyAction="http://tempuri.org/ISignServiceContract/GetBulkSignSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.InvalidSessionFault), Action="http://tempuri.org/ISignServiceContract/GetBulkSignSettingsInvalidSessionFaultFau" +
            "lt", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsSign.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ISignServiceContract/GetBulkSignSettingsArchiflowServiceExcept" +
            "ionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsSign.ResultInfo GetBulkSignSettings(out int SIGN_SERVICE_TYPE, out string HSM_URL_WEB_SERVICE, out string HSM_TYPEOTPAUTH, out string HSM_CERTID, out string HSM_TYPEHSM, out string credential, string strGuidConnect);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignServiceContractChannel : OCF_Ws.WsSign.ISignServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignServiceContractClient : System.ServiceModel.ClientBase<OCF_Ws.WsSign.ISignServiceContract>, OCF_Ws.WsSign.ISignServiceContract {
        
        public SignServiceContractClient() {
        }
        
        public SignServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OCF_Ws.WsSign.ResultInfo InitializeSignRequest(out OCF_Ws.WsSign.RemoteSignResponse oRemoteSignResponse, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest) {
            return base.Channel.InitializeSignRequest(out oRemoteSignResponse, strSessionId, oRequest);
        }
        
        public OCF_Ws.WsSign.ResultInfo ConfirmSignRequest(out OCF_Ws.WsSign.RemoteSignTask oRemoteSignTask, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest, string strXmlUnsignedHashes, long nTaskId) {
            return base.Channel.ConfirmSignRequest(out oRemoteSignTask, strSessionId, oRequest, strXmlUnsignedHashes, nTaskId);
        }
        
        public OCF_Ws.WsSign.ResultInfo AbortSignRequest(string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest, long nTaskId) {
            return base.Channel.AbortSignRequest(strSessionId, oRequest, nTaskId);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetUserCertificate(out string strCertificate, string strSessionId, OCF_Ws.WsSign.RemoteSignRequest oRequest) {
            return base.Channel.GetUserCertificate(out strCertificate, strSessionId, oRequest);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetSignTimeStampFileInfo(out OCF_Ws.WsSign.SignTimeStampFileInfo oSignTimeStampFileInfo, OCF_Ws.WsSign.SessionInfo oSessionInfo, string FileName, byte[] FileContent, bool bDecryptFile) {
            return base.Channel.GetSignTimeStampFileInfo(out oSignTimeStampFileInfo, oSessionInfo, FileName, FileContent, bDecryptFile);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetDigestForMassiveSign(out string strXMLOut, string strGuidConnect, System.Collections.Generic.List<System.Guid> oCardIds, byte[] Certificate, OCF_Ws.WsSign.DigestTarget Target) {
            return base.Channel.GetDigestForMassiveSign(out strXMLOut, strGuidConnect, oCardIds, Certificate, Target);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetAttachmentsDigestForMassiveSign(out string strXMLOut, string strGuidConnect, System.Guid oCardId, System.Collections.Generic.List<int> oAttNames, byte[] Certificate, OCF_Ws.WsSign.DigestTarget Target) {
            return base.Channel.GetAttachmentsDigestForMassiveSign(out strXMLOut, strGuidConnect, oCardId, oAttNames, Certificate, Target);
        }
        
        public OCF_Ws.WsSign.ResultInfo UploadCardsSigned(out string strXMLOut, string strGuidConnect, string strXmlSignedHashes) {
            return base.Channel.UploadCardsSigned(out strXMLOut, strGuidConnect, strXmlSignedHashes);
        }
        
        public OCF_Ws.WsSign.ResultInfo UploadAttachmentsSigned(out string strXMLOut, string strGuidConnect, string strXmlSignedHashes) {
            return base.Channel.UploadAttachmentsSigned(out strXMLOut, strGuidConnect, strXmlSignedHashes);
        }
        
        public OCF_Ws.WsSign.ResultInfo IsX509Certificate2Valid(out System.Collections.Generic.List<string> logList, string strGuidConnect, System.Security.Cryptography.X509Certificates.X509Certificate2 oX509Certificate, System.Nullable<System.DateTime> oCheckDateTime) {
            return base.Channel.IsX509Certificate2Valid(out logList, strGuidConnect, oX509Certificate, oCheckDateTime);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetRemoteSignType(out OCF_Ws.WsSign.SignServiceType SignType, string strGuidConnect) {
            return base.Channel.GetRemoteSignType(out SignType, strGuidConnect);
        }
        
        public OCF_Ws.WsSign.ResultInfo GetBulkSignSettings(out int SIGN_SERVICE_TYPE, out string HSM_URL_WEB_SERVICE, out string HSM_TYPEOTPAUTH, out string HSM_CERTID, out string HSM_TYPEHSM, out string credential, string strGuidConnect) {
            return base.Channel.GetBulkSignSettings(out SIGN_SERVICE_TYPE, out HSM_URL_WEB_SERVICE, out HSM_TYPEOTPAUTH, out HSM_CERTID, out HSM_TYPEHSM, out credential, strGuidConnect);
        }
    }
}
