//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siav.APFlibrary.WsOcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainDocument", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class MainDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BinaryContentField;
        
        private string FilenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BinaryContent {
            get {
                return this.BinaryContentField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryContentField, value) != true)) {
                    this.BinaryContentField = value;
                    this.RaisePropertyChanged("BinaryContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Outcome", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class Outcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int iCodeField;
        
        private string sDescriptionField;
        
        private string sTransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int iCode {
            get {
                return this.iCodeField;
            }
            set {
                if ((this.iCodeField.Equals(value) != true)) {
                    this.iCodeField = value;
                    this.RaisePropertyChanged("iCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string sDescription {
            get {
                return this.sDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescriptionField, value) != true)) {
                    this.sDescriptionField = value;
                    this.RaisePropertyChanged("sDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string sTransactionId {
            get {
                return this.sTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.sTransactionIdField, value) != true)) {
                    this.sTransactionIdField = value;
                    this.RaisePropertyChanged("sTransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class Attachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BinaryContentField;
        
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BinaryContent {
            get {
                return this.BinaryContentField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryContentField, value) != true)) {
                    this.BinaryContentField = value;
                    this.RaisePropertyChanged("BinaryContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Siav.APFlibrary.WsOcf.Agraf> AnagraficaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Siav.APFlibrary.WsOcf.Attachment> AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ClassificazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataProtocolloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdInternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProtocolloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Siav.APFlibrary.WsOcf.MainDocument MainDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MetaDatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OggettoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipologiaDocumentaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Siav.APFlibrary.WsOcf.Visibility VisibilitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Siav.APFlibrary.WsOcf.Agraf> Anagrafica {
            get {
                return this.AnagraficaField;
            }
            set {
                if ((object.ReferenceEquals(this.AnagraficaField, value) != true)) {
                    this.AnagraficaField = value;
                    this.RaisePropertyChanged("Anagrafica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivio {
            get {
                return this.ArchivioField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivioField, value) != true)) {
                    this.ArchivioField = value;
                    this.RaisePropertyChanged("Archivio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Siav.APFlibrary.WsOcf.Attachment> Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Classificazione {
            get {
                return this.ClassificazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificazioneField, value) != true)) {
                    this.ClassificazioneField = value;
                    this.RaisePropertyChanged("Classificazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDocumento {
            get {
                return this.DataDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataDocumentoField, value) != true)) {
                    this.DataDocumentoField = value;
                    this.RaisePropertyChanged("DataDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataProtocollo {
            get {
                return this.DataProtocolloField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProtocolloField, value) != true)) {
                    this.DataProtocolloField = value;
                    this.RaisePropertyChanged("DataProtocollo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdInterno {
            get {
                return this.IdInternoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdInternoField, value) != true)) {
                    this.IdInternoField = value;
                    this.RaisePropertyChanged("IdInterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProtocollo {
            get {
                return this.IdProtocolloField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProtocolloField, value) != true)) {
                    this.IdProtocolloField = value;
                    this.RaisePropertyChanged("IdProtocollo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Siav.APFlibrary.WsOcf.MainDocument MainDocument {
            get {
                return this.MainDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.MainDocumentField, value) != true)) {
                    this.MainDocumentField = value;
                    this.RaisePropertyChanged("MainDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> MetaDati {
            get {
                return this.MetaDatiField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDatiField, value) != true)) {
                    this.MetaDatiField = value;
                    this.RaisePropertyChanged("MetaDati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Oggetto {
            get {
                return this.OggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.OggettoField, value) != true)) {
                    this.OggettoField = value;
                    this.RaisePropertyChanged("Oggetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipologiaDocumentale {
            get {
                return this.TipologiaDocumentaleField;
            }
            set {
                if ((object.ReferenceEquals(this.TipologiaDocumentaleField, value) != true)) {
                    this.TipologiaDocumentaleField = value;
                    this.RaisePropertyChanged("TipologiaDocumentale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Siav.APFlibrary.WsOcf.Visibility Visibilita {
            get {
                return this.VisibilitaField;
            }
            set {
                if ((object.ReferenceEquals(this.VisibilitaField, value) != true)) {
                    this.VisibilitaField = value;
                    this.RaisePropertyChanged("Visibilita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visibility", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class Visibility : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> GruppiDescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> GruppiDescrizioneCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> UfficiCodiceUOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> UfficiCodiceUOCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> UtentiUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> UtentiUserIdCCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> GruppiDescrizione {
            get {
                return this.GruppiDescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.GruppiDescrizioneField, value) != true)) {
                    this.GruppiDescrizioneField = value;
                    this.RaisePropertyChanged("GruppiDescrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> GruppiDescrizioneCC {
            get {
                return this.GruppiDescrizioneCCField;
            }
            set {
                if ((object.ReferenceEquals(this.GruppiDescrizioneCCField, value) != true)) {
                    this.GruppiDescrizioneCCField = value;
                    this.RaisePropertyChanged("GruppiDescrizioneCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> UfficiCodiceUO {
            get {
                return this.UfficiCodiceUOField;
            }
            set {
                if ((object.ReferenceEquals(this.UfficiCodiceUOField, value) != true)) {
                    this.UfficiCodiceUOField = value;
                    this.RaisePropertyChanged("UfficiCodiceUO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> UfficiCodiceUOCC {
            get {
                return this.UfficiCodiceUOCCField;
            }
            set {
                if ((object.ReferenceEquals(this.UfficiCodiceUOCCField, value) != true)) {
                    this.UfficiCodiceUOCCField = value;
                    this.RaisePropertyChanged("UfficiCodiceUOCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> UtentiUserId {
            get {
                return this.UtentiUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UtentiUserIdField, value) != true)) {
                    this.UtentiUserIdField = value;
                    this.RaisePropertyChanged("UtentiUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> UtentiUserIdCC {
            get {
                return this.UtentiUserIdCCField;
            }
            set {
                if ((object.ReferenceEquals(this.UtentiUserIdCCField, value) != true)) {
                    this.UtentiUserIdCCField = value;
                    this.RaisePropertyChanged("UtentiUserIdCC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agraf", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class Agraf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressBookField;
        
        private string Id1Field;
        
        private string Id2Field;
        
        private string Id3Field;
        
        private string TypeEntityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AddressBook {
            get {
                return this.AddressBookField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressBookField, value) != true)) {
                    this.AddressBookField = value;
                    this.RaisePropertyChanged("AddressBook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id1 {
            get {
                return this.Id1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Id1Field, value) != true)) {
                    this.Id1Field = value;
                    this.RaisePropertyChanged("Id1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id2 {
            get {
                return this.Id2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Id2Field, value) != true)) {
                    this.Id2Field = value;
                    this.RaisePropertyChanged("Id2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id3 {
            get {
                return this.Id3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Id3Field, value) != true)) {
                    this.Id3Field = value;
                    this.RaisePropertyChanged("Id3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TypeEntity {
            get {
                return this.TypeEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeEntityField, value) != true)) {
                    this.TypeEntityField = value;
                    this.RaisePropertyChanged("TypeEntity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainDocumentChecked", Namespace="http://schemas.datacontract.org/2004/07/OCF_Ws.Model")]
    [System.SerializableAttribute()]
    public partial class MainDocumentChecked : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BinaryContentField;
        
        private string FilenameField;
        
        private string OutcomeCheckField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BinaryContent {
            get {
                return this.BinaryContentField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryContentField, value) != true)) {
                    this.BinaryContentField = value;
                    this.RaisePropertyChanged("BinaryContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OutcomeCheck {
            get {
                return this.OutcomeCheckField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeCheckField, value) != true)) {
                    this.OutcomeCheckField = value;
                    this.RaisePropertyChanged("OutcomeCheck");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsOcf.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/setMainDocument", ReplyAction="http://tempuri.org/IServices/setMainDocumentResponse")]
        Siav.APFlibrary.WsOcf.Outcome setMainDocument(string sUserName, string sPassword, Siav.APFlibrary.WsOcf.MainDocument oMainDoc, string sGuidCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/setAttachment", ReplyAction="http://tempuri.org/IServices/setAttachmentResponse")]
        Siav.APFlibrary.WsOcf.Outcome setAttachment(string sUserName, string sPassword, Siav.APFlibrary.WsOcf.Attachment Attachment, string sGuidCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/setInternalAttachment", ReplyAction="http://tempuri.org/IServices/setInternalAttachmentResponse")]
        Siav.APFlibrary.WsOcf.Outcome setInternalAttachment(string sUserName, string sPassword, string sGuidCardFrom, string sGuidCardTo, string Note, string sInternalNote, bool bBiunivocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/setCard", ReplyAction="http://tempuri.org/IServices/setCardResponse")]
        Siav.APFlibrary.WsOcf.Outcome setCard(out string sGuidCard, string usernName, string password, Siav.APFlibrary.WsOcf.Card card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getCard", ReplyAction="http://tempuri.org/IServices/getCardResponse")]
        Siav.APFlibrary.WsOcf.Outcome getCard(out Siav.APFlibrary.WsOcf.Card card, string usernName, string password, string sGuidCard, bool bGetMainDoc, bool bGetAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/base64ToPdfA", ReplyAction="http://tempuri.org/IServices/base64ToPdfAResponse")]
        Siav.APFlibrary.WsOcf.Outcome base64ToPdfA(out Siav.APFlibrary.WsOcf.MainDocument mainDocOut, Siav.APFlibrary.WsOcf.MainDocument mainDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/createPdfAFromTemplate", ReplyAction="http://tempuri.org/IServices/createPdfAFromTemplateResponse")]
        Siav.APFlibrary.WsOcf.Outcome createPdfAFromTemplate(out Siav.APFlibrary.WsOcf.MainDocument mainDocOut, System.Collections.Generic.List<System.Collections.Generic.List<string>> aReplaceNameValue, string sGuidCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getIndexConfigFromTypeDocument", ReplyAction="http://tempuri.org/IServices/getIndexConfigFromTypeDocumentResponse")]
        Siav.APFlibrary.WsOcf.Outcome getIndexConfigFromTypeDocument(out System.Collections.Generic.List<string> lstIndexFieldKey, string username, string password, string sTipologiaDocumentale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getSignCheck", ReplyAction="http://tempuri.org/IServices/getSignCheckResponse")]
        Siav.APFlibrary.WsOcf.Outcome getSignCheck(out Siav.APFlibrary.WsOcf.MainDocumentChecked mainDocOut, Siav.APFlibrary.WsOcf.MainDocument mainDoc, string sCRC32, System.Collections.Generic.List<string> lNIN, bool bGetDocWithoutSign);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : Siav.APFlibrary.WsOcf.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<Siav.APFlibrary.WsOcf.IServices>, Siav.APFlibrary.WsOcf.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Siav.APFlibrary.WsOcf.Outcome setMainDocument(string sUserName, string sPassword, Siav.APFlibrary.WsOcf.MainDocument oMainDoc, string sGuidCard) {
            return base.Channel.setMainDocument(sUserName, sPassword, oMainDoc, sGuidCard);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome setAttachment(string sUserName, string sPassword, Siav.APFlibrary.WsOcf.Attachment Attachment, string sGuidCard) {
            return base.Channel.setAttachment(sUserName, sPassword, Attachment, sGuidCard);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome setInternalAttachment(string sUserName, string sPassword, string sGuidCardFrom, string sGuidCardTo, string Note, string sInternalNote, bool bBiunivocal) {
            return base.Channel.setInternalAttachment(sUserName, sPassword, sGuidCardFrom, sGuidCardTo, Note, sInternalNote, bBiunivocal);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome setCard(out string sGuidCard, string usernName, string password, Siav.APFlibrary.WsOcf.Card card) {
            return base.Channel.setCard(out sGuidCard, usernName, password, card);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome getCard(out Siav.APFlibrary.WsOcf.Card card, string usernName, string password, string sGuidCard, bool bGetMainDoc, bool bGetAttachment) {
            return base.Channel.getCard(out card, usernName, password, sGuidCard, bGetMainDoc, bGetAttachment);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome base64ToPdfA(out Siav.APFlibrary.WsOcf.MainDocument mainDocOut, Siav.APFlibrary.WsOcf.MainDocument mainDoc) {
            return base.Channel.base64ToPdfA(out mainDocOut, mainDoc);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome createPdfAFromTemplate(out Siav.APFlibrary.WsOcf.MainDocument mainDocOut, System.Collections.Generic.List<System.Collections.Generic.List<string>> aReplaceNameValue, string sGuidCard) {
            return base.Channel.createPdfAFromTemplate(out mainDocOut, aReplaceNameValue, sGuidCard);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome getIndexConfigFromTypeDocument(out System.Collections.Generic.List<string> lstIndexFieldKey, string username, string password, string sTipologiaDocumentale) {
            return base.Channel.getIndexConfigFromTypeDocument(out lstIndexFieldKey, username, password, sTipologiaDocumentale);
        }
        
        public Siav.APFlibrary.WsOcf.Outcome getSignCheck(out Siav.APFlibrary.WsOcf.MainDocumentChecked mainDocOut, Siav.APFlibrary.WsOcf.MainDocument mainDoc, string sCRC32, System.Collections.Generic.List<string> lNIN, bool bGetDocWithoutSign) {
            return base.Channel.getSignCheck(out mainDocOut, mainDoc, sCRC32, lNIN, bGetDocWithoutSign);
        }
    }
}
