//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCF_Ws.WsLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class ConnectionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExecutiveOfficeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.Language LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.LoginMode ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemDomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenSessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseSystemUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowDomainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFormatField, value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExecutiveOfficeCode {
            get {
                return this.ExecutiveOfficeCodeField;
            }
            set {
                if ((this.ExecutiveOfficeCodeField.Equals(value) != true)) {
                    this.ExecutiveOfficeCodeField = value;
                    this.RaisePropertyChanged("ExecutiveOfficeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.Language Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginTicket {
            get {
                return this.LoginTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginTicketField, value) != true)) {
                    this.LoginTicketField = value;
                    this.RaisePropertyChanged("LoginTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.LoginMode Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemDomain {
            get {
                return this.SystemDomainField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemDomainField, value) != true)) {
                    this.SystemDomainField = value;
                    this.RaisePropertyChanged("SystemDomain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSess {
            get {
                return this.TokenSessField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessField, value) != true)) {
                    this.TokenSessField = value;
                    this.RaisePropertyChanged("TokenSess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseSystemUser {
            get {
                return this.UseSystemUserField;
            }
            set {
                if ((this.UseSystemUserField.Equals(value) != true)) {
                    this.UseSystemUserField = value;
                    this.RaisePropertyChanged("UseSystemUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowDomain {
            get {
                return this.WorkflowDomainField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowDomainField, value) != true)) {
                    this.WorkflowDomainField = value;
                    this.RaisePropertyChanged("WorkflowDomain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum Language : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Italian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        German = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        French = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portuguese = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brasilian = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Romanian = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginMode", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum LoginMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangePassword = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginTicketSap = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginMaintenance = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.BaseClass.Types")]
    public enum ResultInfo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERVER_ERROR = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoggableBase", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Common.Tools.Log")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.SessionInfo))]
    public partial class LoggableBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionInfo", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class SessionInfo : OCF_Ws.WsLogin.LoggableBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CharacterSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ClientTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ExecutiveOfficeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.OfficeChart[] ExecutiveOfficesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.Language LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginTicketUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.UserLoginType LoginTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenSessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VelocisDatabaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VelocisServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short CharacterSet {
            get {
                return this.CharacterSetField;
            }
            set {
                if ((this.CharacterSetField.Equals(value) != true)) {
                    this.CharacterSetField = value;
                    this.RaisePropertyChanged("CharacterSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ClientType {
            get {
                return this.ClientTypeField;
            }
            set {
                if ((this.ClientTypeField.Equals(value) != true)) {
                    this.ClientTypeField = value;
                    this.RaisePropertyChanged("ClientType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFormatField, value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExecutiveOfficeCode {
            get {
                return this.ExecutiveOfficeCodeField;
            }
            set {
                if ((this.ExecutiveOfficeCodeField.Equals(value) != true)) {
                    this.ExecutiveOfficeCodeField = value;
                    this.RaisePropertyChanged("ExecutiveOfficeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.OfficeChart[] ExecutiveOffices {
            get {
                return this.ExecutiveOfficesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutiveOfficesField, value) != true)) {
                    this.ExecutiveOfficesField = value;
                    this.RaisePropertyChanged("ExecutiveOffices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.Language Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginTicketUserId {
            get {
                return this.LoginTicketUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginTicketUserIdField, value) != true)) {
                    this.LoginTicketUserIdField = value;
                    this.RaisePropertyChanged("LoginTicketUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.UserLoginType LoginType {
            get {
                return this.LoginTypeField;
            }
            set {
                if ((this.LoginTypeField.Equals(value) != true)) {
                    this.LoginTypeField = value;
                    this.RaisePropertyChanged("LoginType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenSess {
            get {
                return this.TokenSessField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessField, value) != true)) {
                    this.TokenSessField = value;
                    this.RaisePropertyChanged("TokenSess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VelocisDatabase {
            get {
                return this.VelocisDatabaseField;
            }
            set {
                if ((object.ReferenceEquals(this.VelocisDatabaseField, value) != true)) {
                    this.VelocisDatabaseField = value;
                    this.RaisePropertyChanged("VelocisDatabase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VelocisServer {
            get {
                return this.VelocisServerField;
            }
            set {
                if ((object.ReferenceEquals(this.VelocisServerField, value) != true)) {
                    this.VelocisServerField = value;
                    this.RaisePropertyChanged("VelocisServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowId {
            get {
                return this.WorkflowIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowIdField, value) != true)) {
                    this.WorkflowIdField = value;
                    this.RaisePropertyChanged("WorkflowId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeChart", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Chart.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class OfficeChart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ChildrenOfficesIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExecutiveOfficeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ChildrenOfficesIds {
            get {
                return this.ChildrenOfficesIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenOfficesIdsField, value) != true)) {
                    this.ChildrenOfficesIdsField = value;
                    this.RaisePropertyChanged("ChildrenOfficesIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExecutiveOffice {
            get {
                return this.IsExecutiveOfficeField;
            }
            set {
                if ((this.IsExecutiveOfficeField.Equals(value) != true)) {
                    this.IsExecutiveOfficeField = value;
                    this.RaisePropertyChanged("IsExecutiveOffice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginType", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum UserLoginType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlWorkflow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlGed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UlForcedGed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.UserAccountDisabledFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordLengthFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFormatFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidExecutiveOfficeFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoginTicketSapFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ParamValidationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.AccessDeniedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoginFault))]
    public partial class BaseFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsComErrorInternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InternalCode {
            get {
                return this.InternalCodeField;
            }
            set {
                if ((this.InternalCodeField.Equals(value) != true)) {
                    this.InternalCodeField = value;
                    this.RaisePropertyChanged("InternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComErrorInternalCode {
            get {
                return this.IsComErrorInternalCodeField;
            }
            set {
                if ((this.IsComErrorInternalCodeField.Equals(value) != true)) {
                    this.IsComErrorInternalCodeField = value;
                    this.RaisePropertyChanged("IsComErrorInternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccountDisabledFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class UserAccountDisabledFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidSessionFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidPasswordFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidPasswordLengthFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidPasswordLengthFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidPasswordFormatFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidPasswordFormatFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidExecutiveOfficeFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class InvalidExecutiveOfficeFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginTicketSapFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class LoginTicketSapFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamValidationFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class ParamValidationFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessDeniedFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class AccessDeniedFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
    [System.SerializableAttribute()]
    public partial class LoginFault : OCF_Ws.WsLogin.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
    [System.SerializableAttribute()]
    public partial class ArchiflowServiceExceptionDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.ArchiflowExceptionSeverity SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HResultCode {
            get {
                return this.HResultCodeField;
            }
            set {
                if ((this.HResultCodeField.Equals(value) != true)) {
                    this.HResultCodeField = value;
                    this.RaisePropertyChanged("HResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.ArchiflowExceptionSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiflowExceptionSeverity", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
    public enum ArchiflowExceptionSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessInfo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseOption", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ConnectionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.SessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LicenseOption[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ArchiflowDomain[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ArchiflowDomain))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.Language))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoginMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.UserLoginType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LicenseOptions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LicenseOptions[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.DomainType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.Database_Type))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.Database_Type_Ex))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoggableBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.OfficeChart[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.OfficeChart))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoginFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.BaseFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.UserAccountDisabledFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordLengthFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFormatFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.InvalidExecutiveOfficeFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.LoginTicketSapFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ParamValidationFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.AccessDeniedFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ArchiflowExceptionSeverity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.BaseInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.BaseOutput))]
    public partial class LicenseOption : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.LicenseOptions IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.LicenseOptions Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStringValue {
            get {
                return this.IsStringValueField;
            }
            set {
                if ((this.IsStringValueField.Equals(value) != true)) {
                    this.IsStringValueField = value;
                    this.RaisePropertyChanged("IsStringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiflowDomain", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class ArchiflowDomain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OCF_Ws.WsLogin.DomainType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OCF_Ws.WsLogin.DomainType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordInput", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordInput : OCF_Ws.WsLogin.BaseInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmPassword {
            get {
                return this.ConfirmPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmPasswordField, value) != true)) {
                    this.ConfirmPasswordField = value;
                    this.RaisePropertyChanged("ConfirmPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordOutput", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Login.ValueObject" +
        "")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordOutput : OCF_Ws.WsLogin.BaseOutput {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseOptions", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum LicenseOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoWorkFlow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoMultiLanguage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoDigitalSign = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoElectronicSign = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoExternalMail = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoExtendedMail = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoWebLink = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoCustomerName = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoFullText = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoFullTextOCR = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoAipa = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoSignPdf = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoPosteOnLine = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoPECManagerSE = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoSvAOLSDK = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoWfWorkProcessing = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoWFWorkflowPortal = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoADPWebPortal = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoLegalSafe = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoTitolarioFascArc = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoIFlow = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoContentDiscovery = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        svLoSDKWebServices = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        svLoPECManagerEE = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        svLoGraphometricSign = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoExpirationDate = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoElectronicInvoice = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoBlueDriveIntegration = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoSNA = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoTaskOnDemand = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoAddIn = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoElectronicMark = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoElectronicStamping = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoAutoEmailClass = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInteracDashboard = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoSap = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoMassivePECManager = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoElectronicInvoiceXML = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerIn = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerOut = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerSDIcoop = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerPecPeo = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerDataTransm = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInvoiceManagerADP = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoGdpr = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoInteractivePortal = 45,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainType", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum DomainType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_UNDEFINED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NTUSER = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NTMACHINE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NTGROUP = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NTDOMAIN = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NETWORK = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_ARC_USER = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_ARC_GROUP = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_ARC_OFFICE = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_ADSI_NAMESPACE = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_LDAP_DOMAIN = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_LDAP_OU = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_LDAP_CONTAINER = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_LDAP_GROUP = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_LDAP_USER = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_WINNT_USER = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_WINNT_GROUP = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_WINNT_DOMAIN = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_AOL_USER = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_AOL_GROUP = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_AOL_OFFICE = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_AOL_USER_SUPERVISOR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_AOL_USER_ADMINISTRATOR = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WF_NTDOMAIN_USERS = 23,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Database_Type", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum Database_Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTNotDefined = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTVelocis = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTOracle10 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTOracle11 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Database_Type_Ex", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities.Types")]
    public enum Database_Type_Ex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTNotDefined = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTVelocis = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTOracle = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseInput", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordInput))]
    public partial class BaseInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private OCF_Ws.WsLogin.SessionInfo SessionInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public OCF_Ws.WsLogin.SessionInfo SessionInfo {
            get {
                return this.SessionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionInfoField, value) != true)) {
                    this.SessionInfoField = value;
                    this.RaisePropertyChanged("SessionInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseOutput", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordOutput))]
    public partial class BaseOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsLogin.ILoginServiceContract")]
    public interface ILoginServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/Login", ReplyAction="http://tempuri.org/ILoginServiceContract/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginFault), Action="http://tempuri.org/ILoginServiceContract/LoginLoginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.UserAccountDisabledFault), Action="http://tempuri.org/ILoginServiceContract/LoginUserAccountDisabledFaultFault", Name="UserAccountDisabledFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordFault), Action="http://tempuri.org/ILoginServiceContract/LoginChangePasswordFaultFault", Name="ChangePasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/LoginInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFault), Action="http://tempuri.org/ILoginServiceContract/LoginInvalidPasswordFaultFault", Name="InvalidPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordLengthFault), Action="http://tempuri.org/ILoginServiceContract/LoginInvalidPasswordLengthFaultFault", Name="InvalidPasswordLengthFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFormatFault), Action="http://tempuri.org/ILoginServiceContract/LoginInvalidPasswordFormatFaultFault", Name="InvalidPasswordFormatFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidExecutiveOfficeFault), Action="http://tempuri.org/ILoginServiceContract/LoginInvalidExecutiveOfficeFaultFault", Name="InvalidExecutiveOfficeFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/LoginArchiflowServiceExceptionDetailFaul" +
            "t", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginTicketSapFault), Action="http://tempuri.org/ILoginServiceContract/LoginLoginTicketSapFaultFault", Name="LoginTicketSapFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ParamValidationFault), Action="http://tempuri.org/ILoginServiceContract/LoginParamValidationFaultFault", Name="ParamValidationFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.AccessDeniedFault), Action="http://tempuri.org/ILoginServiceContract/LoginAccessDeniedFaultFault", Name="AccessDeniedFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        OCF_Ws.WsLogin.ResultInfo Login(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/LoginWithDeviceId", ReplyAction="http://tempuri.org/ILoginServiceContract/LoginWithDeviceIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithDeviceIdLoginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithDeviceIdInvalidSessionFaultFaul" +
            "t", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/LoginWithDeviceIdArchiflowServiceExcepti" +
            "onDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo LoginWithDeviceId(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strDeviceid, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceIdWhiteList", ReplyAction="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceIdWhiteListR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceIdWhiteListL" +
            "oginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceIdWhiteListI" +
            "nvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceIdWhiteListA" +
            "rchiflowServiceExceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo LoginWithCredentialAndDeviceIdWhiteList(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, string strDeviceid, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceToken", ReplyAction="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceTokenRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceTokenLoginFa" +
            "ultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceTokenInvalid" +
            "SessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/LoginWithCredentialAndDeviceTokenArchifl" +
            "owServiceExceptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo LoginWithCredentialAndDeviceToken(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, string strDeviceToken, bool bSave, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/Logout", ReplyAction="http://tempuri.org/ILoginServiceContract/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/LogoutInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/LogoutArchiflowServiceExceptionDetailFau" +
            "lt", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo Logout(OCF_Ws.WsLogin.SessionInfo oSessionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetLicense", ReplyAction="http://tempuri.org/ILoginServiceContract/GetLicenseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetLicenseInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetLicenseArchiflowServiceExceptionDetai" +
            "lFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetLicense(out OCF_Ws.WsLogin.LicenseOption[] oLicenses, string strSessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetLicenses", ReplyAction="http://tempuri.org/ILoginServiceContract/GetLicensesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetLicensesInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetLicensesArchiflowServiceExceptionDeta" +
            "ilFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetLicenses(out OCF_Ws.WsLogin.LicenseOption[] oLicenses, string strSessionId, OCF_Ws.WsLogin.LicenseOptions[] oLicenseOptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetSingleLicense", ReplyAction="http://tempuri.org/ILoginServiceContract/GetSingleLicenseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetSingleLicenseInvalidSessionFaultFault" +
            "", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetSingleLicenseArchiflowServiceExceptio" +
            "nDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetSingleLicense(out OCF_Ws.WsLogin.LicenseOption oLicense, string strSessionId, OCF_Ws.WsLogin.LicenseOptions oLicenseOption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetDomains", ReplyAction="http://tempuri.org/ILoginServiceContract/GetDomainsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetDomainsInvalidSessionFaultFault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetDomainsArchiflowServiceExceptionDetai" +
            "lFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetDomains(out OCF_Ws.WsLogin.ArchiflowDomain[] oDomains);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetDatabase_Type", ReplyAction="http://tempuri.org/ILoginServiceContract/GetDatabase_TypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetDatabase_TypeInvalidSessionFaultFault" +
            "", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetDatabase_TypeArchiflowServiceExceptio" +
            "nDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetDatabase_Type(out OCF_Ws.WsLogin.Database_Type eDatabase_Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/GetDatabase_Type_Ex", ReplyAction="http://tempuri.org/ILoginServiceContract/GetDatabase_Type_ExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/GetDatabase_Type_ExInvalidSessionFaultFa" +
            "ult", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/GetDatabase_Type_ExArchiflowServiceExcep" +
            "tionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        OCF_Ws.WsLogin.ResultInfo GetDatabase_Type_Ex(out OCF_Ws.WsLogin.Database_Type_Ex eDatabase_Type_Ex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParam", ReplyAction="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.LoginFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamLoginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ChangePasswordFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamChangePasswordFault" +
            "Fault", Name="ChangePasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidSessionFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamInvalidSessionFault" +
            "Fault", Name="InvalidSessionFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamInvalidPasswordFaul" +
            "tFault", Name="InvalidPasswordFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordLengthFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamInvalidPasswordLeng" +
            "thFaultFault", Name="InvalidPasswordLengthFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.InvalidPasswordFormatFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamInvalidPasswordForm" +
            "atFaultFault", Name="InvalidPasswordFormatFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ArchiflowServiceExceptionDetail), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamArchiflowServiceExc" +
            "eptionDetailFault", Name="ArchiflowServiceExceptionDetail", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Exceptions")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.ParamValidationFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamParamValidationFaul" +
            "tFault", Name="ParamValidationFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(OCF_Ws.WsLogin.AccessDeniedFault), Action="http://tempuri.org/ILoginServiceContract/ChangePasswordByParamAccessDeniedFaultFa" +
            "ult", Name="AccessDeniedFault", Namespace="http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")]
        OCF_Ws.WsLogin.ChangePasswordOutput ChangePasswordByParam(OCF_Ws.WsLogin.ChangePasswordInput paramIn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceContractChannel : OCF_Ws.WsLogin.ILoginServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceContractClient : System.ServiceModel.ClientBase<OCF_Ws.WsLogin.ILoginServiceContract>, OCF_Ws.WsLogin.ILoginServiceContract {
        
        public LoginServiceContractClient() {
        }
        
        public LoginServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OCF_Ws.WsLogin.ResultInfo Login(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo) {
            return base.Channel.Login(out oSessionInfo, strUser, strPassword, oConnectionInfo);
        }
        
        public OCF_Ws.WsLogin.ResultInfo LoginWithDeviceId(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strDeviceid, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo) {
            return base.Channel.LoginWithDeviceId(out oSessionInfo, strDeviceid, oConnectionInfo);
        }
        
        public OCF_Ws.WsLogin.ResultInfo LoginWithCredentialAndDeviceIdWhiteList(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, string strDeviceid, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo) {
            return base.Channel.LoginWithCredentialAndDeviceIdWhiteList(out oSessionInfo, strUser, strPassword, strDeviceid, oConnectionInfo);
        }
        
        public OCF_Ws.WsLogin.ResultInfo LoginWithCredentialAndDeviceToken(out OCF_Ws.WsLogin.SessionInfo oSessionInfo, string strUser, string strPassword, string strDeviceToken, bool bSave, OCF_Ws.WsLogin.ConnectionInfo oConnectionInfo) {
            return base.Channel.LoginWithCredentialAndDeviceToken(out oSessionInfo, strUser, strPassword, strDeviceToken, bSave, oConnectionInfo);
        }
        
        public OCF_Ws.WsLogin.ResultInfo Logout(OCF_Ws.WsLogin.SessionInfo oSessionInfo) {
            return base.Channel.Logout(oSessionInfo);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetLicense(out OCF_Ws.WsLogin.LicenseOption[] oLicenses, string strSessionId) {
            return base.Channel.GetLicense(out oLicenses, strSessionId);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetLicenses(out OCF_Ws.WsLogin.LicenseOption[] oLicenses, string strSessionId, OCF_Ws.WsLogin.LicenseOptions[] oLicenseOptions) {
            return base.Channel.GetLicenses(out oLicenses, strSessionId, oLicenseOptions);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetSingleLicense(out OCF_Ws.WsLogin.LicenseOption oLicense, string strSessionId, OCF_Ws.WsLogin.LicenseOptions oLicenseOption) {
            return base.Channel.GetSingleLicense(out oLicense, strSessionId, oLicenseOption);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetDomains(out OCF_Ws.WsLogin.ArchiflowDomain[] oDomains) {
            return base.Channel.GetDomains(out oDomains);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetDatabase_Type(out OCF_Ws.WsLogin.Database_Type eDatabase_Type) {
            return base.Channel.GetDatabase_Type(out eDatabase_Type);
        }
        
        public OCF_Ws.WsLogin.ResultInfo GetDatabase_Type_Ex(out OCF_Ws.WsLogin.Database_Type_Ex eDatabase_Type_Ex) {
            return base.Channel.GetDatabase_Type_Ex(out eDatabase_Type_Ex);
        }
        
        public OCF_Ws.WsLogin.ChangePasswordOutput ChangePasswordByParam(OCF_Ws.WsLogin.ChangePasswordInput paramIn) {
            return base.Channel.ChangePasswordByParam(paramIn);
        }
    }
}
